# Azure DevOps Pipeline running CI

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
  tags:
    include:
      - v2*

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*

resources:
  containers:
    - container: golang
      image: registry.access.redhat.com/ubi8/go-toolset:1.20.10
      options: --user=0
    - container: python
      image: registry.access.redhat.com/ubi8/python-39:latest
      options: --user=0

variables:
  - template: vars.yml

jobs:

  - job: Golang_Unit_Tests
    variables:
      GOCACHE: /tmp/gocache
    steps:
      - template: ./templates/template-checkout.yml

      - script: |
          set -xe
          go version
          go env
        displayName: Print Go version & env
        target: golang
