name: release-note
on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Generate Changelog
        run: |
          git describe --abbrev=0
          git describe --tags --abbrev=0
          CURRENT_TAG=$(git describe --abbrev=0)
          PREVIOUS_TAG=$(git describe --abbrev=0 $CURRENT_TAG^)
          CHANGELOG=${{ github.workspace }}/CHANGELOG.txt

          cat <<EOF > $CHANGELOG
          $(git tag -l --format='%(contents)' $CURRENT_TAG)

          <details><summary><b>Changes</b></summary>

          $(git log --oneline --no-decorate $PREVIOUS_TAG..$CURRENT_TAG)

          **Full Changelog**: https://github.com/Azure/ARO-RP/compare/$PREVIOUS_TAG...$CURRENT_TAG
          </details>
          EOF
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
